In [1]:
#create array using numpy
#create 1D array

import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row and 5 columns


array([[1, 2, 3, 4, 5]])

In [ ]:
#2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [5]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
#identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
## numpy vectorized operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#element wise addition

print("addition:",arr1+arr2)

#element wise substraction
print("substraction:",arr1-arr2)


addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]


In [ ]:
#universal function
arr=np.array([2,3,4,5,6])
#square root
print(np.sqrt(arr))

#exp 
print(np.exp(arr))

#sine
print(np.sin(arr))

#log

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [12]:
# array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
arr[0][0]

1

In [15]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [16]:
#modify array elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
## statistical concept - Normalization
# to have a mean of 0 and standard deviation of 1

data=np.array([1,2,3,4,5])

mean=np.mean(data)
std_dev=np.std(data)

#Normalize the data

normalized_data=(data-mean)/std_dev

print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [20]:
## logical opeartion

data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)] 

array([5, 6, 7, 8])